name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-platform support, faster builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using token
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ensure your Docker Hub username is set in GitHub secrets
          password: ${{ secrets.DOCKER_TOKEN }}      # Ensure your Docker Hub token is set in GitHub secrets

      # Step 4: Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                            # Set the build context
          file: ./Dockerfile                    # Path to your Dockerfile
          platforms: linux/amd64                # Specify the target platform
          push: true                            # Push the image after building
          tags: kirabo793/docease-frontend:latest  # Tag your Docker image

      # Step 5: Verify the image has been pushed (optional)
      - name: Verify Docker image
        run: |
          docker pull kirabo793/docease-frontend:latest  # Attempt to pull the image to verify it was pushed successfully
